version: 2

models:
  - name: daily_account_summary
    tests:
      - unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - account_id
              - transaction_date
    columns:
      - name: account_id
        tests:
          - not_null
      - name: transaction_date
        tests:
          - not_null
      - name: total_debit_amount
        tests:
          - not_null
      - name: total_credit_amount
        tests:
          - not_null
      - name: net_amount
        tests:
          - not_null
      - name: transaction_count
        tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: ">= 1"
      - name: distinct_merchants
        tests:
          - not_null
      - name: top_category
      - name: currencies
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
