version: 2

models:
  - name: stg_transactions_valid
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
      - name: account_id
        tests:
          - not_null
      - name: transaction_date
        tests:
          - not_null
      - name: currency
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["USD", "EUR", "GBP", "CHF", "JPY", "AUD", "CAD"]
      - name: transaction_type
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["debit", "credit"]
      - name: status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["completed", "pending", "failed", "reversed"]
      - name: is_duplicate
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]
                quote: false
